### ISSUE TITLE
Documentation and Errors Using degauss/census_tracts

### ISSUE THREAD

**Issue by vikjam** [cole-brokamp/DeGAUSS#1]
First of all, thanks so much for making DeGAUSS open-source. This has actually been one of the most pain-free ways to geocode locally that I've used. 

I was having a bit of trouble with degauss/census_tracts. In particular, I'm running a virtual machine on DigitalOcean (Ubuntu 16.04 LTS) to test things out. I'm able to run the docker container to geocode the three addresses you use as a test, which returns a CSV of the geocoded addresses. I then try to run degauss/census_tracts on the output from degauss/geocode, but all I get is a progress bar "(down)loading all county shapefiles" and then it ends. It also leaves a directory such as "RtmpmdnJf0". 

I was wondering if there's any additional document you can point me to troubleshoot degauss/census_tract or if I can provide you with any additional information.

**Comment by cole-brokamp** [comment]
This sounds like an issue where the underlying tigris package is not able to download the all counties shapefile, possible due to internet access on the machine?  You could test this by running  `tigris::counties()` in an R session, although it would require installation of R and the package.

Unfortunately, there isn't a great way to troubleshoot other than to start the container while overriding the entrypoint and try to run the R code inside the container. Start the container with 

`docker run -it --entrypoint /bin/bash degauss/census_tracts`

This will give you a bash prompt inside the container. From there, start `R` and test run the tigris function:

`counties <- tigris::counties()`

Do the counties download?

**Comment by vikjam** [comment]
Thanks! I think you identified the exact issue. Seems like I was running out of RAM at that point (I'm running this test on a low-powered machine). Adding swap space seemed to help, but if I want to run this on a larger dataset, I'll need more RAM. Thanks for your help!

```{bash}
sudo /bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=1024
sudo /sbin/mkswap /var/swap.1
sudo /sbin/swapon /var/swap.1
sudo sh -c 'echo "/var/swap.1 swap swap defaults 0 0 " >> /etc/fstab'
```
via http://deanattali.com/2015/05/09/setup-rstudio-shiny-server-digital-ocean/
