### ISSUE TITLE
as_function() error in Geocoding guide 

### ISSUE THREAD

**Issue by Dolan-Brian** [cole-brokamp/DeGAUSS#14]
When calling Docker image I get the following error:
``` r 
Error: `as_function()` is defunct as of purrr 0.3.0.
Please use `as_mapper()` or `rlang::as_function()` instead
Execution halted.
```
Running on Ubuntu 16.04 and Docker CE.

**Comment by cole-brokamp** [comment]
Thanks for the issue!  This was a problem because DeGAUSS internally depends on the `CB` package for `R`, which in turn depends on `purrr`.  A recent rebuild on [DockerHub](https://cloud.docker.com/u/degauss/repository/docker/degauss/geocoder/general) caused the most recent version of `purrr`, which has made `as_function()` defunct, to be installed.  I've fixed this upstream in https://github.com/cole-brokamp/CB/commit/41618f0e3ad8694a1aa1c3d53591b80b1f3403aa and the DeGAUSS images have been rebuilt and are testing to be working again.  Please reopen if you have any more related problems.

**Comment by Dolan-Brian** [comment]
Cole, thanks for the quick response and resolution. New images worked perfectly. However, I'm now getting an RStudio error in which the file can't be opened. I can view the file in terminal but it can't be added in Git either. Both of these are due to permission denied errors. Also, file.exists() is TRUE for the new '_geocoded' file. Thanks again.

**Comment by cole-brokamp** [comment]
I believe this has to do with the fact that Docker runs as "root" so if it creates a file, then a non-root user does not have permission to edit it.  Is it possible for you to change the permissions on the file using a system command?  `sudo ...`

**Comment by Dolan-Brian** [comment]
Cole, thanks for the response. You pointed me in the right direction, it wasn't a matter of permissions per se but that of ```USER:GROUP```. Using ```chown``` I changed ownership of the file to a non-root user.

**Comment by Dolan-Brian** [comment]
Cole, any guides similar to the 'Geocoding with DeGAUSS'? Was using ../census_tracts but was getting a parse_args error because I was passing the column name still. Didn't realize I didn't have to provide it. Thanks again!

**Comment by cole-brokamp** [comment]
We recently overhauled the documentation -- you can find info about using the geomarker containers here: https://github.com/cole-brokamp/DeGAUSS/wiki/Geomarker-Assessment-with-DeGAUSS

I've tried to move a lot to the wiki.  You'll see that the biggest difference is just not providing the column name since all the geomarker assessment images rely on there being `lat` and `lon` columns in the input file.  The easiest route might be to use the output of the geocoder image directly as the input to the other geomarker images.

**Comment by cakmakaf** [comment]
Thanks very much Cole, the 

Error: `as_function()` is defunct as of purrr 0.3.0.
Please use `as_mapper()` or `rlang::as_function()` instead
Execution halted.

has gone once I pull the latest "docker pull degauss/geocoder"
Best!
