### ISSUE TITLE
Caching income file

### ISSUE THREAD

**Issue by davidfasel** [cole-brokamp/DeGAUSS#20]
I'm trying to geocode 350k addresses.  I split multiple files of 10k lines. I frequently get the error below (when running income), and the program will fail.  I know that's already an issue, and since my files are 10k lines long, it's hard to identify the failing address.  What makes it especially hard to troubleshoot is that the Median household income file has to re-download every time the program is run.  If that file could be cached, it would help tremendously in running a binary search to find the offending rows.  Alternatively, would it be possible to get a line number in the file when these errors are generated?  Thanks so much.  This software is much appreciated.

```
downloading Median household income in the past 12 months (in 2015 Inflation-adjusted dollars) from 2015 5-year American Community Survey

Error in parse_con(txt, bigint_as_char) : parse error: premature EOF

                     (right here) ------^
Calls: map_df ... <Anonymous> -> fromJSON_string -> parseJSON -> parse_con
Execution halted
```

**Comment by davidfasel** [comment]
I was able to determine that addresses in the Virgin Islands fail.  But that doesn't account for all failures.  I'll continue to investigate.

**Comment by cole-brokamp** [comment]
Could it be something with how you are splitting the files?  Seems like "premature end of file" might be something to do with line or file endings?

Unfortunately, this error is coming from the ruby part of the code, so it would be hard to report back a line number for which the failure is happening.

If you are interested in the income, you might want to try using another DeGAUSS container we have made available here: https://github.com/cole-brokamp/cchmc_batch_geocoder

This container works similarly to degauss except that it expects addresses in a column named `address`.  We've also added some extra steps so that it will scrub addresses of non-alphanumeric characters (which could also be the root of the premature EOF file error above), and it also adds on census tracts as well as our deprivation index and its 6 components (more details on that here: https://github.com/cole-brokamp/dep_index). It also doesn't require downloading the census tract level data everytime -- it is included in the docker image.
