### ISSUE TITLE
Column Order is inconsistent over multiple runs of the Geocoding

### ISSUE THREAD

**Issue by jschappet** [cole-brokamp/DeGAUSS#5]
When Processing multiple files the output _geocoded.csv file column ordering is inconsistent.

```
head -1 new_*_geo*
==> new_a_geocoded.csv <==
"address","X...id","street","zip","score","prenum","number","precision","lon","lat","city","state","street1","street2"

==> new_b_geocoded.csv <==
"address","X...id","street","zip","city","state","lat","lon","score","prenum","number","precision","street1","street2","X[[i]]"

==> new_c_geocoded.csv <==
"address","X...id","street","zip","city","state","lat","lon","score","prenum","number","precision","X[[i]]","street1","street2"

==> new_d_geocoded.csv <==
"address","X...id","street","zip","city","state","lat","lon","score","prenum","number","precision","street1","street2","X[[i]]"

==> new_e_geocoded.csv <==
"address","X...id","street","zip","city","state","lat","lon","score","prenum","number","precision","X[[i]]","street1","street2"
```

Please set the output column order to a consistent format

**Comment by itelligentllc** [comment]
I have experienced the same issue when processing multiple files. I ended up creating a python script to loop through my _geocoded files and put the columns in a consistent order.

**Comment by cole-brokamp** [comment]
Thanks for the feedback. This is a little trickier than just pre-specifying column order because I would like the software to return all of the original columns that were submitted.  I'm open to pull requests for this, but be sure to see https://github.com/cole-brokamp/geocoder/issues/2 and https://github.com/cole-brokamp/geocoder/pull/3 for further discussion.
