### ISSUE TITLE
Typo in README.md /tmp -> /temp

### ISSUE THREAD

**Issue by jschappet** [cole-brokamp/DeGAUSS#6]
I ran into a problem running the Geocoder, my file was not being found when running geocoding.

```
# BROKEN
 $ docker run --rm=TRUE -v "$PWD":/tmp  degauss/geocoder /tmp/new_h  address
```

```
# GOOD  temp, not tmp
 $ docker run --rm=TRUE -v "$PWD":/temp  degauss/geocoder /temp/new_h  address
```

**Comment by cole-brokamp** [comment]
Thanks for your feedback and interest in DeGAUSS.  I think that your problem is arising from specifying the path to the address CSV file.  There is not a typo and `$PWD` should indeed be mounted to `/tmp` and not `/temp`. Try specifying the address CSV file with the `.csv` extension in the filename and without the entire path.  Just the name of the file in the current working directory should be sufficient because DeGAUSS works by setting the working directory to `/tmp` inside R.

Closing this issue for now, but please let me know if you run into any other problems.
