### ISSUE TITLE
invalid FIPS code or state name/abbreviation

### ISSUE THREAD

**Issue by jschappet** [cole-brokamp/DeGAUSS#7]
I'm running into a problem with the census_tracts process:

`
Error: Invalid state
In addition: Warning message:
'69' is not a valid FIPS code or state name/abbreviation 
Execution halted
`

Is there a good way to identify the problematic address?

**Comment by cole-brokamp** [comment]
Unfortunately, there is not a good way to debug without shelling into the docker container and running the R code "natively".  Based on the error message, I'm guessing that one of your geocodes is being assigned to a FIPS county with a state identifier of 69 (Commonwealth of the Northern Mariana Islands) and then the "tigris" package in R cannot download the tract shapefile for this area since it is not in the us tracts shapefile.

**Comment by cole-brokamp** [comment]
Closing now since we haven't heard from you in awhile, but please reopen if the problem persists.
